version: "0.2"
words:
  - aarch
  - addch
  - addnab
  - addstr
  - androideabi
  - armhf
  - armv
  - attroff
  - attron
  - autorefs
  - autoupdate
  - bindgen
  - binstall
  - bitfield
  - bndy
  - bytearray
  - calcsize
  - cbreak
  - Cdev
  - cdylib
  - clippy
  - codecov
  - corepack
  - crossrefs
  - datasheet
  - defmt
  - Dmitry
  - Doherty
  - dtolnay
  - DYNPD
  - eabi
  - EDDYSTONE
  - endfor
  - endl
  - endlineno
  - endmacro
  - endwin
  - fontawesome
  - gnueabihf
  - gpio
  - gpiocdev
  - gpiochip
  - gpiod
  - Grinberg
  - HLINE
  - hustcer
  - inlinehilite
  - isnan
  - istr
  - Kbps
  - libc
  - libgpiod
  - libnghttp
  - linenums
  - manylinux
  - maturin
  - Mbps
  - milliwatts
  - mkdocs
  - mkdocstrings
  - mosi
  - MSRV
  - msvc
  - multiceiver
  - musleabihf
  - musllinux
  - mypy
  - nanos
  - nanosleep
  - napi
  - nextest
  - nocbreak
  - nodenext
  - noecho
  - nonconstructor
  - nonoctal
  - npmjs
  - nurfile
  - nushell
  - opengpio
  - oxlint
  - pipx
  - pkgid
  - pyclass
  - pyfunction
  - pymdown
  - pymdownx
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pyproject
  - repr
  - reshim
  - RETR
  - riscv
  - rustc
  - rustup
  - RXADDR
  - sccache
  - SCLK
  - sdist
  - Spidev
  - startswith
  - staticmethod
  - struct
  - superfences
  - taiki
  - tasklist
  - timeit
  - tlsv
  - twemoji
  - typdedoc
  - yarnrc
  - zigbuild
  - zizmor
ignorePaths:
  - .yarn
  - "**/.gitignore"
  - "**/.cargo"
  - .config/cliff.toml
